/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#272a32",
        "surface-bright": "#363942",
        "surface-container-highest": "#32353d",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed": "#ffdbca",
        "tertiary-container": "#e86d16",
        "surface-container": "#1d1f27",
        "on-tertiary-container": "#4a1c00",
        "on-surface-variant": "#c2c6d7",
        "on-error-container": "#ffdad6",
        "primary-container": "#548dff",
        "on-secondary-fixed": "#002113",
        "background": "#10131b",
        "on-primary-fixed-variant": "#00429a",
        "secondary": "#4edea3",
        "on-secondary-container": "#00311f",
        "secondary-container": "#00a572",
        "secondary-fixed": "#6ffbbe",
        "surface-tint": "#afc6ff",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0b0e15",
        "surface-container-low": "#191b23",
        "inverse-primary": "#0058c9",
        "outline": "#8c90a0",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#773200",
        "primary-fixed-dim": "#afc6ff",
        "on-primary-fixed": "#001944",
        "on-error": "#690005",
        "on-tertiary": "#542100",
        "surface-dim": "#10131b",
        "primary-fixed": "#d9e2ff",
        "inverse-surface": "#e1e2ed",
        "on-secondary": "#003824",
        "on-primary": "#002d6d",
        "outline-variant": "#424754",
        "on-background": "#e1e2ed",
        "on-tertiary-fixed": "#331100",
        "inverse-on-surface": "#2d3039",
        "tertiary-fixed-dim": "#ffb68f",
        "on-primary-container": "#002760",
        "on-surface": "#e1e2ed",
        "secondary-fixed-dim": "#4edea3",
        "primary": "#afc6ff",
        "surface-variant": "#32353d",
        "tertiary": "#ffb68f",
        "surface": "#10131b"
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "display-lg": ["Inter"]
      },
      spacing: {
        "gutter": "24px",
        "container-padding-desktop": "32px",
        "base": "8px",
        "container-padding-mobile": "16px",
        "card-gap": "16px"
      }
    },
  },
  plugins: [],
}
